# services:
#   app:
#     image: focusflow:v1
#     build:
#       context: .
#       dockerfile: Dockerfile
#     # environment:
#     #   - PORT=8002
#     #   - DATABASE_URL=postgresql+psycopg://time-user:time-pw@db_service:5432/timescaledb
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"
#     command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
#     volumes:
#       - ./backend:/app:rw
#     develop:
#       watch:
#         - action: rebuild
#           path: Dockerfile
#         - action: rebuild
#           path: requirements.txt
#         - action: rebuild
#           path: docker-compose.yml
services:
  app:
    image: focusflow:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:rw
    environment:
      - DJANGO_ENV=development
      - PORT=8000
    command: /opt/run.sh
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yml
